# -*- coding: utf-8 -*-
"""Chatbot2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ddZ3NdGcCSru0YBxzbPg8cDI_VnUxebJ
"""

import streamlit as st
import time

# ----------------------------------------------------
# 🎨 ESTILOS PERSONALIZADOS PREMIUM + AVATARES
# ----------------------------------------------------
st.markdown("""
    <style>

    body, .stApp {
        background-color: #f3e9dd !important;
        background-image: radial-gradient(circle at top left, #f7f0e7, #e9dcc5);
        background-attachment: fixed;
    }

    .title-container h1 {
        color: #4b2e19 !important;
        font-family: 'Segoe UI', sans-serif;
        font-weight: 700;
    }

    .user-bubble {
        background: #ffffff !important;
        padding: 12px 18px;
        border-radius: 18px;
        margin: 10px 0;
        border: 2px solid #d7c7b5;
        color: #3b2a1e;
        font-size: 16px;
        display: inline-block;
        animation: fadeIn 0.4s ease;
    }

    .bot-bubble {
        background: #f0e6d9 !important;
        padding: 12px 18px;
        border-radius: 18px;
        margin: 10px 0;
        border: 2px solid #c6b39d;
        color: #3b2a1e;
        font-size: 16px;
        display: inline-block;
        animation: fadeIn 0.4s ease;
    }

    @keyframes fadeIn {
        from {opacity: 0; transform: translateY(5px);}
        to {opacity: 1; transform: translateY(0);}
    }

    input {
        background: #fffaf3 !important;
        border-radius: 12px !important;
        border: 2px solid #c4a98a !important;
        color: #4a3524 !important;
    }

    input:focus {
        border: 2px solid #8b5e34 !important;
        box-shadow: 0 0 6px #c2a37a !important;
    }

    button {
        background: #8b5e34 !important;
        color: white !important;
        border-radius: 10px !important;
        padding: 8px 16px !important;
        border: none !important;
    }

    button:hover {
        background: #704a28 !important;
    }

    </style>
""", unsafe_allow_html=True)


# ----------------------------------------------------
# 💰 Catálogo de productos
# ----------------------------------------------------
catalogo_productos = {
    "café": [
        {"nombre": "Café Solo", "precio": 1200},
        {"nombre": "Café Doble", "precio": 1500},
        {"nombre": "Café con Leche", "precio": 1600},
        {"nombre": "Capuchino", "precio": 2000},
        {"nombre": "Latte", "precio": 2100},
    ],
    "té": [
        {"nombre": "Té Clásico Negro", "precio": 1100},
        {"nombre": "Té Verde", "precio": 1200},
        {"nombre": "Té con Leche", "precio": 1300},
        {"nombre": "Té de Manzanilla", "precio": 1200},
    ]
}


# ----------------------------------------------------
# 🧠 MODELO LLM SIN SABOR NI INTENSIDAD
# ----------------------------------------------------
class RecomendadorLLM:
    def __init__(self):
        self.estado = "inicio"
        self.tipo_seleccionado = None

    def _call(self, prompt: str) -> str:
        texto = prompt.lower().strip()

        # INICIO
        if self.estado == "inicio":
            self.estado = "tipo_bebida"
            return "👋 ¡Hola! Bienvenido/a soy tu Asistente virtual. ¿Querés café o té hoy?"

        # ELEGIR CAFE O TE
        elif self.estado == "tipo_bebida":
            if "café" in texto or "cafe" in texto:
                self.tipo_seleccionado = "café"
                self.estado = "mostrar_menu"
                return "Perfecto ☕ Te muestro nuestra carta de cafés:"

            elif "té" in texto or "te" in texto:
                self.tipo_seleccionado = "té"
                self.estado = "mostrar_menu"
                return "Genial 🍵 Te muestro nuestra carta de tés:"

            return "Decime si preferís *café* o *té*."

        # ESPERA QUE EL USUARIO ELIJA DESDE LA CARTA
        elif self.estado == "mostrar_menu":
            return "Elegí tu bebida tocando un botón en la carta. 😄"

        # CONFIRMAR COMPRA
        elif self.estado == "confirmar_compra":
            if "si" in texto or "sí" in texto or "comprar" in texto:
                self.estado = "inicio"
                return (
                    "🎉 ¡Gracias por tu compra! En minutos estará listo tu pedido.\n"
                    "🔄 Reiniciando asistente..."
                )
            elif "no" in texto:
                self.estado = "inicio"
                return "Todo bien 😊 Si querés otra recomendación, escribime."
            return "Decime *sí* para comprar o *no* para cancelar."

        return "No entendí, ¿podés repetirlo?"


# ----------------------------------------------------
# 🌟 CHAT STREAMLIT CON AVATARES
# ----------------------------------------------------
st.set_page_config(page_title="Café Premium", page_icon="☕")
st.title("☕ Asistente de Café / Té")

avatar_bot = "https://cdn-icons-png.flaticon.com/512/4712/4712100.png"
avatar_user = "https://cdn-icons-png.flaticon.com/512/747/747376.png"

# Estados del chat
if "messages" not in st.session_state:
    st.session_state.messages = []

if "llm" not in st.session_state:
    st.session_state.llm = RecomendadorLLM()


# Mostrar historial
for msg in st.session_state.messages:
    with st.chat_message(msg["role"], avatar=avatar_bot if msg["role"] == "assistant" else avatar_user):
        st.write(msg["content"])


# Entrada usuario
user_input = st.chat_input("Escribí tu pedido...")

if user_input:
    # Mensaje del usuario
    st.session_state.messages.append({"role": "user", "content": user_input})
    with st.chat_message("user", avatar=avatar_user):
        st.write(user_input)

    # Respuesta del bot
    respuesta = st.session_state.llm._call(user_input)
    st.session_state.messages.append({"role": "assistant", "content": respuesta})

    with st.chat_message("assistant", avatar=avatar_bot):
        st.write(respuesta)

    # Reinicio automático
    if "Gracias por tu compra" in respuesta:
        time.sleep(5)
        st.session_state.messages = []
        st.session_state.llm = RecomendadorLLM()
        st.rerun()


# ----------------------------------------------------
# 📜 MOSTRAR CARTA CUANDO CORRESPONDA
# ----------------------------------------------------
if st.session_state.llm.estado == "mostrar_menu":
    tipo = st.session_state.llm.tipo_seleccionado
    productos = catalogo_productos[tipo]

    st.markdown("### 📜 Carta de " + tipo.capitalize())

    cols = st.columns(2)

    for i, p in enumerate(productos):
        with cols[i % 2]:
            if st.button(f"{p['nombre']} - ${p['precio']}"):
                st.session_state.producto_seleccionado = p
                st.session_state.llm.estado = "confirmar_compra"

                mensaje = (
                    f"Elegiste **{p['nombre']}** ☕\n"
                    f"Precio: ${p['precio']}\n\n"
                    "¿Querés comprarlo?"
                )

                st.session_state.messages.append({"role": "assistant", "content": mensaje})
                st.rerun()